### ISSUE TITLE
Title: where is ein-subpackages?

### ISSUE THREAD

**Issue by tvraman** [dickmao/emacs-ipython-notebook#78]
After installing from melpa:

Module ein-subpackages  is not in the ein install.
Note that the "minimal setup" in index.rst suggests doing a require of ein-subpackages.

**Comment by dickmao** [comment]
You continue to reference material in the `doc` subdirectory.  That directory contains only woe and misdirection.  I will delete it soon.

If your .emacs invokes `(package-initialize)` in the normal way, the three ways of invoking EIN as described in the README.rst should work without any additional and expensive `require` statements.
